### ISSUE TITLE
Please fix for this Err: on Thai and Lao lang

### ISSUE THREAD

**Issue by Seng555** [andrey-ushakov/esc_pos_utils#127]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument (string): Contains invalid characters.: "ສິນຄ້າ"
#0      _UnicodeSubsetEncoder.convert (dart:convert/ascii.dart:85:9)
#1      Latin1Codec.encode (dart:convert/latin1.dart:40:46)
#2      Generator._encode (package:esc_pos_utils_plus/src/generator.dart:78:21)
#3      Generator.text (package:esc_pos_utils_plus/src/generator.dart:355:9)
#4      _MyAppState._printReceiveTest (package:printest/main.dart:164:24)

**Comment by Abhis1211** [comment]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument (string): Contains invalid characters.: "जीन्स पैंट नैरो"

how to print hindi word  ?

**Comment by Seng555** [comment]
Where support ?
