### ISSUE TITLE
Not working with Cyrillic

### ISSUE THREAD

**Issue by xaldarof** [andrey-ushakov/esc_pos_utils#84]
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Invalid argument (string): Contains invalid characters.: "Привет"
#0      _UnicodeSubsetEncoder.convert (dart:convert/ascii.dart:85:9)
#1      Latin1Codec.encode (dart:convert/latin1.dart:40:46)
#2      Generator._encode (package:esc_pos_utils/src/generator.dart:77:21)
#3      Generator.text (package:esc_pos_utils/src/generator.dart:354:9)
#4      PrinterUsb.printReceipt (package:erp_desktop/printer/printer_usb.dart:86:27)
<asynchronous suspension>

**Comment by vipros123** [comment]
@xaldarof  Use Plugin https://pub.dev/packages/flutter_esc_pos_utils
with codec utf8
